coverage_service: cobertura_xml
source_directory: AsyncTCP
output_directory: report
xcodeproj: AsyncTCP.xcodeproj
workspace: AsyncTCP.xcworkspace
scheme: AsyncTCP-macOS
ignore:
  - AsyncTCPTests/*
  - Assets/*