language: objective-c
osx_image: xcode10.3

branches:
 only:
 - master

before_script:
- bundle install

git:
  quiet: true

jobs:
  include:
    - stage: "Tests"
      name: "iOS"
      script: fastlane ios tests
    - name: "macOS"
      script: fastlane mac tests
