language: objective-c
osx_image: xcode10.3

before_install:
- bundle install

git:
  quiet: true

jobs:
  include:
    - stage: "Tests"
      name: "iOS"
      script: fastlane ios tests
    - name: "macOS"
      script: fastlane mac tests

after_success:
  - slather
