language: objective-c
osx_image: xcode10.3

before_install:
- bundle install

git:
  quiet: true

jobs:
  include:
    - stage: "Tests"
      name: "iOS"
      script: fastlane ios tests
    - name: "macOS"
      script: fastlane mac tests

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
